# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/applog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_applog(object):
    def setupUi(self, applog):
        applog.setObjectName("applog")
        applog.resize(355, 276)
        self.centralwidget = QtWidgets.QWidget(applog)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 361, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(200, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm.setFont(font)
        self.confirm.setObjectName("confirm")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 61, 111, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(40, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close.setFont(font)
        self.close.setObjectName("close")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 101, 111, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.card_password = QtWidgets.QLineEdit(self.centralwidget)
        self.card_password.setGeometry(QtCore.QRect(120, 110, 141, 31))
        self.card_password.setObjectName("card_password")
        self.card_number = QtWidgets.QLineEdit(self.centralwidget)
        self.card_number.setGeometry(QtCore.QRect(120, 70, 141, 31))
        self.card_number.setObjectName("card_number")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(40, 230, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.help.setFont(font)
        self.help.setObjectName("help")
        applog.setCentralWidget(self.centralwidget)

        self.retranslateUi(applog)
        QtCore.QMetaObject.connectSlotsByName(applog)

    def retranslateUi(self, applog):
        _translate = QtCore.QCoreApplication.translate
        applog.setWindowTitle(_translate("applog", "MainWindow"))
        self.label_3.setText(_translate("applog", "APP登陆界面🏦"))
        self.confirm.setText(_translate("applog", "确认登录"))
        self.label_2.setText(_translate("applog", "卡号"))
        self.close.setText(_translate("applog", "关闭app"))
        self.label_4.setText(_translate("applog", "密码"))
        self.help.setText(_translate("applog", "查看帮助😊？"))
