# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ATMlog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ATMlog(object):
    def setupUi(self, ATMlog):
        ATMlog.setObjectName("ATMlog")
        ATMlog.resize(355, 233)
        self.centralwidget = QtWidgets.QWidget(ATMlog)
        self.centralwidget.setObjectName("centralwidget")
        self.card_number = QtWidgets.QLineEdit(self.centralwidget)
        self.card_number.setGeometry(QtCore.QRect(140, 69, 131, 31))
        self.card_number.setObjectName("card_number")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(30, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.help.setFont(font)
        self.help.setObjectName("help")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 361, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);\n"
"")
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(190, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm.setFont(font)
        self.confirm.setObjectName("confirm")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 100, 81, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.card_password = QtWidgets.QLineEdit(self.centralwidget)
        self.card_password.setGeometry(QtCore.QRect(140, 109, 131, 31))
        self.card_password.setObjectName("card_password")
        ATMlog.setCentralWidget(self.centralwidget)

        self.retranslateUi(ATMlog)
        QtCore.QMetaObject.connectSlotsByName(ATMlog)

    def retranslateUi(self, ATMlog):
        _translate = QtCore.QCoreApplication.translate
        ATMlog.setWindowTitle(_translate("ATMlog", "MainWindow"))
        self.help.setText(_translate("ATMlog", "创建账户"))
        self.label_3.setText(_translate("ATMlog", "ATM登陆界面🏦"))
        self.confirm.setText(_translate("ATMlog", "确认登录"))
        self.label_2.setText(_translate("ATMlog", "卡号"))
        self.label_4.setText(_translate("ATMlog", "密码"))
